modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Fisher Eletric"
authors="fisher_team"
description="A NeoForge mod that adds an electric fishing rod. Hold it near water to automatically generate fishing loot."

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
